//+build !noasm !appengine
// AUTO-GENERATED BY C2GOASM -- DO NOT EDIT

TEXT ·__DotProduct(SB), $0-24

	MOVQ m+0(FP), DI
	MOVQ vec4+8(FP), SI
	MOVQ result+16(FP), DX

	LONG $0x0710fdc5               // vmovupd    ymm0, yword [rdi]
	LONG $0x0659fdc5               // vmulpd    ymm0, ymm0, yword [rsi]
	LONG $0x197de3c4; WORD $0x01c1 // vextractf128    xmm1, ymm0, 1
	LONG $0xc158f9c5               // vaddpd    xmm0, xmm0, xmm1
	LONG $0x0579e3c4; WORD $0x01c8 // vpermilpd    xmm1, xmm0, 1
	LONG $0xc158f9c5               // vaddpd    xmm0, xmm0, xmm1
	LONG $0x0217f9c5               // vmovhpd    qword [rdx], xmm0
	VZEROUPPER
	RET
